services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      bash -c "
        ollama serve &
        sleep 5 &&
        ollama pull gemma3:latest &&
        ollama run gemma3:latest 'Hello' &&
        ollama pull deepseek-coder-v2:latest &&
        ollama run deepseek-coder-v2:latest 'Hello' &&
        tail -f /dev/null
      "
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8801:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - LOG_LEVEL=DEBUG
      - OLLAMA_BASE_URL=http://172.17.0.1:11434
      - DEFAULT_MODEL=gemma3:latest
    depends_on:
      - ollama
    restart: always

volumes:
  ollama_data:
  open-webui:
# docker exec -it ollama ollama run gemma3
