services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      bash -c "
        ollama serve &
        sleep 5 &&
        ollama pull codellama &&
        ollama pull deepseek-coder-v2 &&
        tail -f /dev/null
      "
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8800:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - LOG_LEVEL=DEBUG
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - DEFAULT_MODEL=codellama
    depends_on:
      - ollama
    restart: always

volumes:
  ollama_data:
  open-webui:
# docker exec -it ollama ollama run codellama
